version: "3"
services:
  db:
    volumes:
      - db-volume:/var/lib/postgresql/data
  api:
    command: npm run start:dev
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    volumes:
      - ./client:/app/
      - /app/node_modules
volumes:
  db-volume:
